projects:
  default:
    # TODO: env var
    schema: https://api.graph.cool/relay/v1/next-js-with-relay-modern-example
    extensions:
      codegen:
        ./schema/schema.graphql:
            - schema-ast
