name: 'Chromatic Deployment'
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_MEDIA_ENDPOINT: https://prod-tab2017-media.gladly.io
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Install dependencies
        run: yarn
      - name: set up relay files
        run: yarn run relay
      - uses: chromaui/action@v1
        # Options required for Chromatic's GitHub Action
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          autoAcceptChanges: false
          exitOnceUploaded: true
