# This is a basic workflow to help you get started with Actions

name: E2E tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: merge master to qa
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "gladly-team/tab-web"
          source_branch: "master"
          destination_branch: "qa"
          github_token: ${{ github.token }}
      - name: Set branch name output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - name: Merge feature branch -> qa
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: ${{ github.head_ref }}
          target_branch: qa
          github_token: ${{ github.token }}

